### ISSUE TITLE
Default ES_HEAP_SIZE as a function of total memory

### ISSUE THREAD

**Issue by erik-stephens** [elasticsearch/puppet-elasticsearch#267] opened 2015-02-10 17:56 UTC
Would it be useful to others to to define this default as a function of total memory?  Something like the following is what I typically do but as I move more of my configuration to hiera, this kind of math is not possible:

    $default_heap_size = floor($::memorysize_mb / 2)
    $instance_init_defaults_main = {..., 'ES_HEAP_SIZE' => "${default_heap_size}M"}

**Comment by jvehent** [comment] 2015-02-12 15:13
I second this. I cannot find a way to set the HEAP_SIZE through this module on ubuntu. A parameter would be useful.

**Comment by erik-stephens** [comment] 2015-02-12 15:33
@jvehent You can define it via the [instance's `init_defaults` parameter](https://github.com/elasticsearch/puppet-elasticsearch/blob/12724599a99fe84bc7cc892d4076182d69ee97c9/manifests/instance.pp#L61).  Hope that helps.

**Comment by ajlanghorn** [comment] 2015-02-13 16:30
We'd find it very useful to be able to set the HEAP_SIZE on Ubuntu using a heap_size param. @jvehent, @erik-stephens - have either of you started a branch? I'd be happy to contribute.

**Comment by erik-stephens** [comment] 2015-02-13 16:47
@ajlanghorn Have you tried setting it via `init_defaults`?  It *should* work on Ubuntu as well.  I'm waiting for feedback from the maintainer(s) to confirm that it is a good idea before submitting a PR.

**Comment by ajlanghorn** [comment] 2015-02-13 16:49
@erik-stephens Yes, we do exactly that, and I can confirm it works fine for us on 12.04 LTS.

**Comment by erik-stephens** [comment] 2015-02-13 16:56
@ajlanghorn Cool.  When you say "using a heap_size param", what does that look like?  Is it a percentage?

**Comment by ajlanghorn** [comment] 2015-02-13 16:59
@erik-stephens Yes, pretty much. We set the total heap size allocation to be a percentage of the total RAM on the machine. Elasticsearch have some documentation on best practice guidelines to use for your heap size, and from memory, they suggest using 50% of your available RAM at most. If I can find a link, I'll fire it your way.

**Comment by electrical** [comment] 2015-02-16 11:42
Hi guys.

The 50% of avail memory is correct but we also advise not to use more then 31GB of heap.
Adding all this kind of automatic calculations might confuse people on the long run so i'm not sure yet If this is something i would like to implement but i do appreciate the thought and discussion.

**Comment by electrical** [comment] 2015-02-17 13:36
Hi guys,

gave this some more thought and decided not to implement such an option.
Mainly because it would be 'magic' and can fail in some cases where it might select the wrong amount of memory ( and then cause all kind of weirdness )
As a solution you can always build some kind of wrapper or role class that can define the memory to the ES class in the way you want it.

thank you though for the idea!

**Comment by erik-stephens** [comment] 2015-02-17 14:46
No problem and thanks for the consideration.  People look to Puppet modules to provide opinionated defaults based on best practices.  Allow me to try to clarify/summarize what is being proposed since I don't see it as magical or implicit.  I propose adding a new parameter `heap_size_percent`.  By default, it is undef which keeps the behavior as it is now.  If it is defined, then we do something like:

    $instance_init_defaults_main['ES_HEAP_SIZE'] = floor($::memorysize_mb * $heap_size_percent / 100)

Could be a pretty simple patch - I'd be willing to submit a PR.  It does add complexity in the form of one more parameter to document and extra cases to test.  Also, I can see some complexity with handling when a user defines both `init_defaults['ES_HEAP_SIZE']` and `heap_size_percent`.

Again, no worries if still think it un-wise.  Sometimes less is more.

**Comment by electrical** [comment] 2015-02-17 15:10
Hi @erik-stephens thank you for the clarification.
My main concern is that we might end up with several settings for defining the heap space size.
Also the 50% rule for example states that it shouldn't be more then 31GB, so we will need to check for that as well.
What should we do when we are over the 31GB? fail the whole run or just log a warning?
And indeed conflicting settings, which one will rule then?

**Comment by electrical** [comment] 2015-03-05 14:41
Hi guys.

I will be closing the issue. Gave it more thought in the last few days and decided not to implement this due to several reasons.
Thank you though for the contribution!

**Closed by electrical** 2015-03-05 14:41 UTC

**Comment by ajlanghorn** [comment] 2015-03-05 14:52
@electrical Are those reasons those you outlined above, or are there others? If there are others, could you just put them in this PR for completeness? Thanks!

**Comment by electrical** [comment] 2015-03-05 15:38
@ajlanghorn only the reasons i've mentioned above indeed.
